<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class FormSelectPT
    Inherits System.Windows.Forms.Form

    'Form 重写 Dispose，以清理组件列表。
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Windows 窗体设计器所必需的
    Private components As System.ComponentModel.IContainer

    '注意: 以下过程是 Windows 窗体设计器所必需的
    '可以使用 Windows 窗体设计器修改它。  
    '不要使用代码编辑器修改它。
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim TreeNode1 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.1.1 随机事件的概念（12题）")
        Dim TreeNode2 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.1.2 随机事件的关系（9题）")
        Dim TreeNode3 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.1.3 随机事件的运算（18题）")
        Dim TreeNode4 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.1.4 随机事件间的运算表示（10题）")
        Dim TreeNode5 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.1随机事件（49题）", New System.Windows.Forms.TreeNode() {TreeNode1, TreeNode2, TreeNode3, TreeNode4})
        Dim TreeNode6 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.2.1.1 概率的定义、判断与证明（14题）")
        Dim TreeNode7 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.2.1.2 概率性质的应用（8题）")
        Dim TreeNode8 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.2.1 概率的定义与性质（22题）", New System.Windows.Forms.TreeNode() {TreeNode6, TreeNode7})
        Dim TreeNode9 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.2.2.1 两个事件的概率计算（22题）")
        Dim TreeNode10 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.2.2.2 多个事件的概率计算（10题）")
        Dim TreeNode11 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.2.2 随机事件的概率计算（32题）", New System.Windows.Forms.TreeNode() {TreeNode9, TreeNode10})
        Dim TreeNode12 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.2 随机事件的概率（54题）", New System.Windows.Forms.TreeNode() {TreeNode8, TreeNode11})
        Dim TreeNode13 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.3.1 排列组合计算（10题）")
        Dim TreeNode14 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.3.2.1 古典概型之数字排列、骰子与扑克（25题）")
        Dim TreeNode15 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.3.2.2 古典概型之球的分配（30题）")
        Dim TreeNode16 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.3.2.3 古典概型之人员分配、产品抽样及其它模型（35题")
        Dim TreeNode17 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.3.2 古典概型的概率计算（90题", New System.Windows.Forms.TreeNode() {TreeNode14, TreeNode15, TreeNode16})
        Dim TreeNode18 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.3.3 几何概型的概率计算（5题）")
        Dim TreeNode19 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.3 古典概型和几何概型（105题）", New System.Windows.Forms.TreeNode() {TreeNode13, TreeNode17, TreeNode18})
        Dim TreeNode20 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.4.1 条件概率的定义与性质（19题）")
        Dim TreeNode21 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.4.2.1 条件概率的定义计算（18题）")
        Dim TreeNode22 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.4.2.2 条件概率的应用计算（25题）")
        Dim TreeNode23 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.4.2 条件概率的计算（43题）", New System.Windows.Forms.TreeNode() {TreeNode21, TreeNode22})
        Dim TreeNode24 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.4 条件概率（62题）", New System.Windows.Forms.TreeNode() {TreeNode20, TreeNode23})
        Dim TreeNode25 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.5.1 全概率公式（23题）")
        Dim TreeNode26 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.5.2 贝叶斯公式（6题）")
        Dim TreeNode27 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.5 全概率公式与贝叶斯公式（29题）", New System.Windows.Forms.TreeNode() {TreeNode25, TreeNode26})
        Dim TreeNode28 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.6.1 两个事件的独立性（19题）")
        Dim TreeNode29 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.6.2 多个事件的独立性（12题）")
        Dim TreeNode30 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.6.3事件的独立性应用（31题）")
        Dim TreeNode31 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.6.4 伯努利概型（29题）")
        Dim TreeNode32 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("1.6 事件的独立性（91题）", New System.Windows.Forms.TreeNode() {TreeNode28, TreeNode29, TreeNode30, TreeNode31})
        Dim TreeNode33 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第1章 随机事件与概率（390题）", New System.Windows.Forms.TreeNode() {TreeNode5, TreeNode12, TreeNode19, TreeNode24, TreeNode27, TreeNode32})
        Dim TreeNode34 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.1.1 分布律及其性质(34题)")
        Dim TreeNode35 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.1.2.1.1 二项分布（0-1分布）(28题)")
        Dim TreeNode36 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.1.2.1.2 泊松分布、超几何分布和几何分布(13题)")
        Dim TreeNode37 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.1.2.1 常见的离散型随机变量的概率计算(41题)", New System.Windows.Forms.TreeNode() {TreeNode35, TreeNode36})
        Dim TreeNode38 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.1.2.2 一般离散型随机变量的概率计算(8题)")
        Dim TreeNode39 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.1.2 离散型随机变量的概率计算(49题)", New System.Windows.Forms.TreeNode() {TreeNode37, TreeNode38})
        Dim TreeNode40 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.1 离散型随机变量及其分布(83题)", New System.Windows.Forms.TreeNode() {TreeNode34, TreeNode39})
        Dim TreeNode41 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.1 概率密度及其性质(23题)")
        Dim TreeNode42 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.4.1.1 均匀分布与指数分布(18题)")
        Dim TreeNode43 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.4.1.2 正态分布(14题)")
        Dim TreeNode44 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.4.1 常见连续型随机变量的概率计算(32题)", New System.Windows.Forms.TreeNode() {TreeNode42, TreeNode43})
        Dim TreeNode45 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.4.2 一般连续型随机变量事件的概率计算(27题)")
        Dim TreeNode46 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.4 连续型随机变量的概率计算(59题)", New System.Windows.Forms.TreeNode() {TreeNode44, TreeNode45})
        Dim TreeNode47 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.2 正态分布及其性质(10题)")
        Dim TreeNode48 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2.3 正态分布标准化与应用(19题)")
        Dim TreeNode49 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.2 连续型随机变量及其分布(111题)", New System.Windows.Forms.TreeNode() {TreeNode41, TreeNode46, TreeNode47, TreeNode48})
        Dim TreeNode50 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.3.1 分布函数及其性质(0题)")
        Dim TreeNode51 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.3.2 分布函数与分布律(22题)")
        Dim TreeNode52 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.3.3 分布函数与概率密度(12题)")
        Dim TreeNode53 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.3.4 分布函数与概率计算(13题)")
        Dim TreeNode54 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.3 随机变量的分布函数(47题)", New System.Windows.Forms.TreeNode() {TreeNode50, TreeNode51, TreeNode52, TreeNode53})
        Dim TreeNode55 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.4.1 离散型随机变量的函数的分布(7题)")
        Dim TreeNode56 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.4.2.1 连续函数情形(37题)")
        Dim TreeNode57 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.4.2.2 非连续函数情形(0题)")
        Dim TreeNode58 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.4.2 连续型随机变量的函数的分布(37题)", New System.Windows.Forms.TreeNode() {TreeNode56, TreeNode57})
        Dim TreeNode59 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("2.4 随机变量的函数的分布(44题)", New System.Windows.Forms.TreeNode() {TreeNode55, TreeNode58})
        Dim TreeNode60 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第2章 随机变量及其分布(285题)", New System.Windows.Forms.TreeNode() {TreeNode40, TreeNode49, TreeNode54, TreeNode59})
        Dim TreeNode61 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.1.1 二维离散型随机变量及其分布的概念（0题）")
        Dim TreeNode62 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.1.2 二维连续型随机变量及其分布的概念（18题）")
        Dim TreeNode63 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.1 二维随机变量及其分布的概念（18题）", New System.Windows.Forms.TreeNode() {TreeNode61, TreeNode62})
        Dim TreeNode64 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.1.1 联合分布律（9题）")
        Dim TreeNode65 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.1.2 联合与边缘分布律（1题）")
        Dim TreeNode66 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.1.3 联合与条件分布律（3题）")
        Dim TreeNode67 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.1 二维离散型随机变量的分布律（13题）", New System.Windows.Forms.TreeNode() {TreeNode64, TreeNode65, TreeNode66})
        Dim TreeNode68 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.2.1 三项分布（0题）")
        Dim TreeNode69 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.2.2 二维超几何分布（0题）")
        Dim TreeNode70 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.2 常见的二维离散型随机变量及其分布（0题）", New System.Windows.Forms.TreeNode() {TreeNode68, TreeNode69})
        Dim TreeNode71 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.2.3 二维离散型随机变量的概率计算（15题）")
        Dim TreeNode72 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("" & Global.Microsoft.VisualBasic.ChrW(9) & "3.2 二维离散型随机变量及其分布（28题）", New System.Windows.Forms.TreeNode() {TreeNode67, TreeNode70, TreeNode71})
        Dim TreeNode73 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.1.1 联合概率密度（10题）")
        Dim TreeNode74 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.1.2 联合与边缘概率密度（14题）")
        Dim TreeNode75 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.1.3 联合与条件概率密度（3题）")
        Dim TreeNode76 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.1 二维连续型随机变量的概率密度（27题）", New System.Windows.Forms.TreeNode() {TreeNode73, TreeNode74, TreeNode75})
        Dim TreeNode77 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.2.1 二维均匀分布（17题）")
        Dim TreeNode78 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.2.2 二维正态分布（0题）")
        Dim TreeNode79 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.2 常见的二维连续型随机变量及其分布（17题）", New System.Windows.Forms.TreeNode() {TreeNode77, TreeNode78})
        Dim TreeNode80 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3.3 二维连续型随机变量的概率计算（18题）")
        Dim TreeNode81 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.3 二维连续型随机变量及其分布（62题）", New System.Windows.Forms.TreeNode() {TreeNode76, TreeNode79, TreeNode80})
        Dim TreeNode82 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.4.1 联合分布函数（0题）")
        Dim TreeNode83 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.4.2 联合与边缘分布函数（0题）")
        Dim TreeNode84 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.4.3 联合与条件分布函数（0题）")
        Dim TreeNode85 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.4 二维随机变量的分布函数（0题）", New System.Windows.Forms.TreeNode() {TreeNode82, TreeNode83, TreeNode84})
        Dim TreeNode86 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.1 二维随机变量相互独立的概念（0题）")
        Dim TreeNode87 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.2 离散型随机变量的独立性（13题）")
        Dim TreeNode88 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.3 连续型随机变量的独立性（7题）")
        Dim TreeNode89 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.4.1 二项变量、泊松变量的独立性")
        Dim TreeNode90 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.4.2 均匀变量、指数变量的独立性")
        Dim TreeNode91 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.4.3 正态变量的独立性")
        Dim TreeNode92 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.4 常见随机变量的独立性（11题）", New System.Windows.Forms.TreeNode() {TreeNode89, TreeNode90, TreeNode91})
        Dim TreeNode93 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5.5 n维随机变量的独立性（0题）")
        Dim TreeNode94 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.5 随机变量的独立性（31题）", New System.Windows.Forms.TreeNode() {TreeNode86, TreeNode87, TreeNode88, TreeNode92, TreeNode93})
        Dim TreeNode95 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.6.1 二维离散型随机变量的函数的分布（8题）")
        Dim TreeNode96 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.6.2 二维连续型随机变量的函数的分布（19题）")
        Dim TreeNode97 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.6.3 最大、最小函数的分布（14题）")
        Dim TreeNode98 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.6.4 离散型与连续型随机变量的函数的分布（0题）")
        Dim TreeNode99 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.6.5 n维随机变量的函数的分布（5题）")
        Dim TreeNode100 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("3.6 多维随机变量的函数的分布（46题）", New System.Windows.Forms.TreeNode() {TreeNode95, TreeNode96, TreeNode97, TreeNode98, TreeNode99})
        Dim TreeNode101 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第3章 多维随机变量及其分布（185题）", New System.Windows.Forms.TreeNode() {TreeNode63, TreeNode72, TreeNode81, TreeNode85, TreeNode94, TreeNode100})
        Dim TreeNode102 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.1 数学期望的概念与性质（30题）")
        Dim TreeNode103 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.2.1 离散型随机变量的期望（18题）")
        Dim TreeNode104 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.2.2 连续型随机变量的期望（13题）")
        Dim TreeNode105 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.2 期望计算（31题）", New System.Windows.Forms.TreeNode() {TreeNode103, TreeNode104})
        Dim TreeNode106 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.3.1 一维离散型随机变量的函数的期望（9题）")
        Dim TreeNode107 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.3.2 一维连续型随机变量的函数的期望（12题）")
        Dim TreeNode108 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.3.3 二维离散型随机变量的函数的期望（1题）")
        Dim TreeNode109 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.3.4 二维连续型随机变量的函数的期望（11题）")
        Dim TreeNode110 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.3 随机变量函数的期望（33题）", New System.Windows.Forms.TreeNode() {TreeNode106, TreeNode107, TreeNode108, TreeNode109})
        Dim TreeNode111 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1.4 期望应用（0题）")
        Dim TreeNode112 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.1 数学期望（94题）", New System.Windows.Forms.TreeNode() {TreeNode102, TreeNode105, TreeNode110, TreeNode111})
        Dim TreeNode113 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.1 方差的概念与性质（27题）")
        Dim TreeNode114 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.2.1 离散型随机变量的方差（3题）")
        Dim TreeNode115 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.2.2 连续型随机变量的方差（15题）")
        Dim TreeNode116 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.2 方差计算（18题）", New System.Windows.Forms.TreeNode() {TreeNode114, TreeNode115})
        Dim TreeNode117 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.3.1 一维离散型随机变量的函数的方差（0题）")
        Dim TreeNode118 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.3.2 一维连续型随机变量的函数的方差（0题）")
        Dim TreeNode119 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.3.3二维离散型随机变量的函数的方差（0题）")
        Dim TreeNode120 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.3.4 二维连续型随机变量的函数的方差（0题）")
        Dim TreeNode121 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.3 随机变量的函数的方差（0题）", New System.Windows.Forms.TreeNode() {TreeNode117, TreeNode118, TreeNode119, TreeNode120})
        Dim TreeNode122 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.4 切比雪夫不等式（25题）")
        Dim TreeNode123 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2.5 方差应用（0题）")
        Dim TreeNode124 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.2 方差（70题）", New System.Windows.Forms.TreeNode() {TreeNode113, TreeNode116, TreeNode121, TreeNode122, TreeNode123})
        Dim TreeNode125 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.1.1 常见离散型分布的期望与方差（12题）")
        Dim TreeNode126 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.1.2 常见连续型分布的期望与方差（11题）")
        Dim TreeNode127 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.1 常见分布的期望与方差（23题）", New System.Windows.Forms.TreeNode() {TreeNode125, TreeNode126})
        Dim TreeNode128 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.2.1 离散型随机变量的期望与方差（4题）")
        Dim TreeNode129 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.2.2 离散型随机变量函数的期望与方差（1题）")
        Dim TreeNode130 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.2 一般离散型分布的期望与方差（5题）", New System.Windows.Forms.TreeNode() {TreeNode128, TreeNode129})
        Dim TreeNode131 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.3.1 连续型随机变量的期望与方差（3题）")
        Dim TreeNode132 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.3.2 连续型随机变量函数的期望与方差（8题）")
        Dim TreeNode133 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3.3 一般连续型分布的期望与方差（11题）", New System.Windows.Forms.TreeNode() {TreeNode131, TreeNode132})
        Dim TreeNode134 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.3 期望与方差计算（39题）", New System.Windows.Forms.TreeNode() {TreeNode127, TreeNode130, TreeNode133})
        Dim TreeNode135 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.4.1 协方差的概念与性质（10题）")
        Dim TreeNode136 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.4.2 协方差计算（0题）")
        Dim TreeNode137 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.4.3 相关系数的概念与性质（8题）")
        Dim TreeNode138 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.4.4 相关系数计算（23题）")
        Dim TreeNode139 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.4.5 随机变量的不相关性（8题）")
        Dim TreeNode140 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.4.6 相关系数应用（0题）")
        Dim TreeNode141 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.4 协方差与相关系数（49题）", New System.Windows.Forms.TreeNode() {TreeNode135, TreeNode136, TreeNode137, TreeNode138, TreeNode139, TreeNode140})
        Dim TreeNode142 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.5.1 矩的概念（5题）")
        Dim TreeNode143 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.5.2 矩计算（0题）")
        Dim TreeNode144 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("4.5 矩（5题）", New System.Windows.Forms.TreeNode() {TreeNode142, TreeNode143})
        Dim TreeNode145 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第4章 随机变量的数字特征（257题）", New System.Windows.Forms.TreeNode() {TreeNode112, TreeNode124, TreeNode134, TreeNode141, TreeNode144})
        Dim TreeNode146 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("5.1.1 依概率收敛（0题）")
        Dim TreeNode147 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("5.1.2 三个大数定理（5题）")
        Dim TreeNode148 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("5.1 大数定理（5题）", New System.Windows.Forms.TreeNode() {TreeNode146, TreeNode147})
        Dim TreeNode149 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("5.2.1 两个中心极限定理（9题）")
        Dim TreeNode150 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("5.2.2 两个中心极限定理的应用（17题）")
        Dim TreeNode151 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("5.2 中心极限定理（26题）", New System.Windows.Forms.TreeNode() {TreeNode149, TreeNode150})
        Dim TreeNode152 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第5章 大数定理与中心极限定理（31题）", New System.Windows.Forms.TreeNode() {TreeNode148, TreeNode151})
        Dim TreeNode153 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.1.1 简单随机样本与样本的联合分布（7题）")
        Dim TreeNode154 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.1.2 直方图、条形图及经验分布函数（6题）")
        Dim TreeNode155 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.1 总体与样本（13题）", New System.Windows.Forms.TreeNode() {TreeNode153, TreeNode154})
        Dim TreeNode156 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.2.1 基本数字特征（33题）")
        Dim TreeNode157 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.2.2 简易数字特征（0题）")
        Dim TreeNode158 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.2 样本的数字特征（33题）", New System.Windows.Forms.TreeNode() {TreeNode156, TreeNode157})
        Dim TreeNode159 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.3.1 分位数（0题）")
        Dim TreeNode160 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.3.2 χ2分布、t分布和F分布（28题）")
        Dim TreeNode161 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.3 三个常用的抽样分布（28题）", New System.Windows.Forms.TreeNode() {TreeNode159, TreeNode160})
        Dim TreeNode162 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.1 统计量的概念（6题）")
        Dim TreeNode163 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.2.1 单个正态总体的抽样分布定理（25题）")
        Dim TreeNode164 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.2.2 单个正态总体的抽样应用（19题）")
        Dim TreeNode165 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.2 单个正态总体的抽样分布（44题）", New System.Windows.Forms.TreeNode() {TreeNode163, TreeNode164})
        Dim TreeNode166 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.3.1 两个正态总体的抽样分布定理（13题）")
        Dim TreeNode167 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.3.2 两个正态总体的抽样应用（9题）")
        Dim TreeNode168 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.3 两个正态总体的抽样分布（22题）", New System.Windows.Forms.TreeNode() {TreeNode166, TreeNode167})
        Dim TreeNode169 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4.4 一般总体的抽样分布（16题）")
        Dim TreeNode170 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("6.4 常用统计量及其分布（88题）", New System.Windows.Forms.TreeNode() {TreeNode162, TreeNode165, TreeNode168, TreeNode169})
        Dim TreeNode171 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第6章 样本与抽样分布（162题）", New System.Windows.Forms.TreeNode() {TreeNode155, TreeNode158, TreeNode161, TreeNode170})
        Dim TreeNode172 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.1.1 点估计与区间估计的概念（10题）")
        Dim TreeNode173 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.1.2 估计量（18题）")
        Dim TreeNode174 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.1 参数估计的概念（28题）", New System.Windows.Forms.TreeNode() {TreeNode172, TreeNode173})
        Dim TreeNode175 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.2.1.1 矩估计法（22题）")
        Dim TreeNode176 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.2.1.2 最大似然估计法（13题）")
        Dim TreeNode177 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.2.1 点估计的方法（35题）", New System.Windows.Forms.TreeNode() {TreeNode175, TreeNode176})
        Dim TreeNode178 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.2.2.1 无偏性（24题）")
        Dim TreeNode179 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.2.2.2 有效性和相合性（12题）")
        Dim TreeNode180 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.2.2 点估计量的评价准则（36题）", New System.Windows.Forms.TreeNode() {TreeNode178, TreeNode179})
        Dim TreeNode181 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.2 点估计（71题）", New System.Windows.Forms.TreeNode() {TreeNode177, TreeNode180})
        Dim TreeNode182 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3.1.1 均值的区间估计（23题）")
        Dim TreeNode183 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3.1.2 方差的区间估计（9题）")
        Dim TreeNode184 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3.1 单个正态总体均值与方差的区间估计（32题）", New System.Windows.Forms.TreeNode() {TreeNode182, TreeNode183})
        Dim TreeNode185 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3.2.1 均值差的区间估计（6题）")
        Dim TreeNode186 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3.2.2 方差比的区间估计（4题）")
        Dim TreeNode187 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3.2 两个正态总体均值差与方差比的区间估计（10题）", New System.Windows.Forms.TreeNode() {TreeNode185, TreeNode186})
        Dim TreeNode188 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3.3 一般总体参数的区间估计（11题）")
        Dim TreeNode189 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("7.3 区间估计（53题）", New System.Windows.Forms.TreeNode() {TreeNode184, TreeNode187, TreeNode188})
        Dim TreeNode190 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第7章 参数估计（152题）", New System.Windows.Forms.TreeNode() {TreeNode174, TreeNode181, TreeNode189})
        Dim TreeNode191 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.1.1 假设检验问题（9题）")
        Dim TreeNode192 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("" & Global.Microsoft.VisualBasic.ChrW(9) & "8.1.2 假设检验中的两类错误（15题）")
        Dim TreeNode193 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.1 假设检验的基本概念（24题）", New System.Windows.Forms.TreeNode() {TreeNode191, TreeNode192})
        Dim TreeNode194 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.2.1.1 均值检验（33题）")
        Dim TreeNode195 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.2.1.2 方差检验（20题）")
        Dim TreeNode196 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.2.1 单个正态总体参数的假设检验（53题）", New System.Windows.Forms.TreeNode() {TreeNode194, TreeNode195})
        Dim TreeNode197 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.2.2.1 均值差检验（27题）")
        Dim TreeNode198 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.2.2.2 方差比检验（11题）")
        Dim TreeNode199 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.2.2 两个正态总体参数的假设检验（38题）", New System.Windows.Forms.TreeNode() {TreeNode197, TreeNode198})
        Dim TreeNode200 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.2 正态总体参数的假设检验（91题）", New System.Windows.Forms.TreeNode() {TreeNode196, TreeNode199})
        Dim TreeNode201 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.3 一般总体参数的假设检验（17题）")
        Dim TreeNode202 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("8.4 总体分布的假设检验（12题）")
        Dim TreeNode203 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("第8章 假设检验（144题）", New System.Windows.Forms.TreeNode() {TreeNode193, TreeNode200, TreeNode201, TreeNode202})
        Me.TreeView1 = New System.Windows.Forms.TreeView()
        Me.SuspendLayout()
        '
        'TreeView1
        '
        Me.TreeView1.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.TreeView1.Location = New System.Drawing.Point(12, 12)
        Me.TreeView1.Name = "TreeView1"
        TreeNode1.Name = "3"
        TreeNode1.Text = "1.1.1 随机事件的概念（12题）"
        TreeNode2.Name = "4"
        TreeNode2.Text = "1.1.2 随机事件的关系（9题）"
        TreeNode3.Name = "5"
        TreeNode3.Text = "1.1.3 随机事件的运算（18题）"
        TreeNode4.Name = "9"
        TreeNode4.Text = "1.1.4 随机事件间的运算表示（10题）"
        TreeNode5.Name = "节点0"
        TreeNode5.Text = "1.1随机事件（49题）"
        TreeNode6.Name = "13"
        TreeNode6.Text = "1.2.1.1 概率的定义、判断与证明（14题）"
        TreeNode7.Name = "14"
        TreeNode7.Text = "1.2.1.2 概率性质的应用（8题）"
        TreeNode8.Name = "12"
        TreeNode8.Text = "1.2.1 概率的定义与性质（22题）"
        TreeNode9.Name = "16"
        TreeNode9.Text = "1.2.2.1 两个事件的概率计算（22题）"
        TreeNode10.Name = "17"
        TreeNode10.Text = "1.2.2.2 多个事件的概率计算（10题）"
        TreeNode11.Name = "节点7"
        TreeNode11.Text = "1.2.2 随机事件的概率计算（32题）"
        TreeNode12.Name = "节点5"
        TreeNode12.Text = "1.2 随机事件的概率（54题）"
        TreeNode13.Name = "19"
        TreeNode13.Text = "1.3.1 排列组合计算（10题）"
        TreeNode14.Name = "21"
        TreeNode14.Text = "1.3.2.1 古典概型之数字排列、骰子与扑克（25题）"
        TreeNode15.Name = "22"
        TreeNode15.Text = "1.3.2.2 古典概型之球的分配（30题）"
        TreeNode16.Name = "23"
        TreeNode16.Text = "1.3.2.3 古典概型之人员分配、产品抽样及其它模型（35题"
        TreeNode17.Name = "节点17"
        TreeNode17.Text = "1.3.2 古典概型的概率计算（90题"
        TreeNode18.Name = "24"
        TreeNode18.Text = "1.3.3 几何概型的概率计算（5题）"
        TreeNode19.Name = "节点12"
        TreeNode19.Text = "1.3 古典概型和几何概型（105题）"
        TreeNode20.Name = "26"
        TreeNode20.Text = "1.4.1 条件概率的定义与性质（19题）"
        TreeNode21.Name = "28"
        TreeNode21.Text = "1.4.2.1 条件概率的定义计算（18题）"
        TreeNode22.Name = "29"
        TreeNode22.Text = "1.4.2.2 条件概率的应用计算（25题）"
        TreeNode23.Name = "节点23"
        TreeNode23.Text = "1.4.2 条件概率的计算（43题）"
        TreeNode24.Name = "节点13"
        TreeNode24.Text = "1.4 条件概率（62题）"
        TreeNode25.Name = "31"
        TreeNode25.Text = "1.5.1 全概率公式（23题）"
        TreeNode26.Name = "32"
        TreeNode26.Text = "1.5.2 贝叶斯公式（6题）"
        TreeNode27.Name = "节点14"
        TreeNode27.Text = "1.5 全概率公式与贝叶斯公式（29题）"
        TreeNode28.Name = "34"
        TreeNode28.Text = "1.6.1 两个事件的独立性（19题）"
        TreeNode29.Name = "35"
        TreeNode29.Text = "1.6.2 多个事件的独立性（12题）"
        TreeNode30.Name = "36"
        TreeNode30.Text = "1.6.3事件的独立性应用（31题）"
        TreeNode31.Name = "37"
        TreeNode31.Text = "1.6.4 伯努利概型（29题）"
        TreeNode32.Name = "节点15"
        TreeNode32.Text = "1.6 事件的独立性（91题）"
        TreeNode33.Name = "节点0"
        TreeNode33.Text = "第1章 随机事件与概率（390题）"
        TreeNode34.Name = "39"
        TreeNode34.Text = "2.1.1 分布律及其性质(34题)"
        TreeNode35.Name = "43"
        TreeNode35.Text = "2.1.2.1.1 二项分布（0-1分布）(28题)"
        TreeNode36.Name = "44"
        TreeNode36.Text = "2.1.2.1.2 泊松分布、超几何分布和几何分布(13题)"
        TreeNode37.Name = "节点24"
        TreeNode37.Text = "2.1.2.1 常见的离散型随机变量的概率计算(41题)"
        TreeNode38.Name = "45"
        TreeNode38.Text = "2.1.2.2 一般离散型随机变量的概率计算(8题)"
        TreeNode39.Name = "节点13"
        TreeNode39.Text = "2.1.2 离散型随机变量的概率计算(49题)"
        TreeNode40.Name = "38"
        TreeNode40.Text = "2.1 离散型随机变量及其分布(83题)"
        TreeNode41.Name = "47"
        TreeNode41.Text = "2.2.1 概率密度及其性质(23题)"
        TreeNode42.Name = "52"
        TreeNode42.Text = "2.2.4.1.1 均匀分布与指数分布(18题)"
        TreeNode43.Name = "54"
        TreeNode43.Text = "2.2.4.1.2 正态分布(14题)"
        TreeNode44.Name = "51"
        TreeNode44.Text = "2.2.4.1 常见连续型随机变量的概率计算(32题)"
        TreeNode45.Name = "55"
        TreeNode45.Text = "2.2.4.2 一般连续型随机变量事件的概率计算(27题)"
        TreeNode46.Name = "节点15"
        TreeNode46.Text = "2.2.4 连续型随机变量的概率计算(59题)"
        TreeNode47.Name = "68"
        TreeNode47.Text = "2.2.2 正态分布及其性质(10题)"
        TreeNode48.Name = "110"
        TreeNode48.Text = "2.2.3 正态分布标准化与应用(19题)"
        TreeNode49.Name = "46"
        TreeNode49.Text = "2.2 连续型随机变量及其分布(111题)"
        TreeNode50.Name = "58"
        TreeNode50.Text = "2.3.1 分布函数及其性质(0题)"
        TreeNode51.Name = "59"
        TreeNode51.Text = "2.3.2 分布函数与分布律(22题)"
        TreeNode52.Name = "60"
        TreeNode52.Text = "2.3.3 分布函数与概率密度(12题)"
        TreeNode53.Name = "62"
        TreeNode53.Text = "2.3.4 分布函数与概率计算(13题)"
        TreeNode54.Name = "57"
        TreeNode54.Text = "2.3 随机变量的分布函数(47题)"
        TreeNode55.Name = "64"
        TreeNode55.Text = "2.4.1 离散型随机变量的函数的分布(7题)"
        TreeNode56.Name = "66"
        TreeNode56.Text = "2.4.2.1 连续函数情形(37题)"
        TreeNode57.Name = "67"
        TreeNode57.Text = "2.4.2.2 非连续函数情形(0题)"
        TreeNode58.Name = "节点23"
        TreeNode58.Text = "2.4.2 连续型随机变量的函数的分布(37题)"
        TreeNode59.Name = "63"
        TreeNode59.Text = "2.4 随机变量的函数的分布(44题)"
        TreeNode60.Name = "6"
        TreeNode60.Text = "第2章 随机变量及其分布(285题)"
        TreeNode61.Name = "70"
        TreeNode61.Text = "3.1.1 二维离散型随机变量及其分布的概念（0题）"
        TreeNode62.Name = "71"
        TreeNode62.Text = "3.1.2 二维连续型随机变量及其分布的概念（18题）"
        TreeNode63.Name = "节点32"
        TreeNode63.Text = "3.1 二维随机变量及其分布的概念（18题）"
        TreeNode64.Name = "75"
        TreeNode64.Text = "3.2.1.1 联合分布律（9题）"
        TreeNode65.Name = "76"
        TreeNode65.Text = "3.2.1.2 联合与边缘分布律（1题）"
        TreeNode66.Name = "77"
        TreeNode66.Text = "3.2.1.3 联合与条件分布律（3题）"
        TreeNode67.Name = "节点40"
        TreeNode67.Text = "3.2.1 二维离散型随机变量的分布律（13题）"
        TreeNode68.Name = "80"
        TreeNode68.Text = "3.2.2.1 三项分布（0题）"
        TreeNode69.Name = "81"
        TreeNode69.Text = "3.2.2.2 二维超几何分布（0题）"
        TreeNode70.Name = "节点41"
        TreeNode70.Text = "3.2.2 常见的二维离散型随机变量及其分布（0题）"
        TreeNode71.Name = "78"
        TreeNode71.Text = "3.2.3 二维离散型随机变量的概率计算（15题）"
        TreeNode72.Name = "节点33"
        TreeNode72.Text = "" & Global.Microsoft.VisualBasic.ChrW(9) & "3.2 二维离散型随机变量及其分布（28题）"
        TreeNode73.Name = "84"
        TreeNode73.Text = "3.3.1.1 联合概率密度（10题）"
        TreeNode74.Name = "85"
        TreeNode74.Text = "3.3.1.2 联合与边缘概率密度（14题）"
        TreeNode75.Name = "86"
        TreeNode75.Text = "3.3.1.3 联合与条件概率密度（3题）"
        TreeNode76.Name = "83"
        TreeNode76.Text = "3.3.1 二维连续型随机变量的概率密度（27题）"
        TreeNode77.Name = "88"
        TreeNode77.Text = "3.3.2.1 二维均匀分布（17题）"
        TreeNode78.Name = "89"
        TreeNode78.Text = "3.3.2.2 二维正态分布（0题）"
        TreeNode79.Name = "87"
        TreeNode79.Text = "3.3.2 常见的二维连续型随机变量及其分布（17题）"
        TreeNode80.Name = "90"
        TreeNode80.Text = "3.3.3 二维连续型随机变量的概率计算（18题）"
        TreeNode81.Name = "节点34"
        TreeNode81.Text = "3.3 二维连续型随机变量及其分布（62题）"
        TreeNode82.Name = "92"
        TreeNode82.Text = "3.4.1 联合分布函数（0题）"
        TreeNode83.Name = "93"
        TreeNode83.Text = "3.4.2 联合与边缘分布函数（0题）"
        TreeNode84.Name = "160"
        TreeNode84.Text = "3.4.3 联合与条件分布函数（0题）"
        TreeNode85.Name = "节点35"
        TreeNode85.Text = "3.4 二维随机变量的分布函数（0题）"
        TreeNode86.Name = "95"
        TreeNode86.Text = "3.5.1 二维随机变量相互独立的概念（0题）"
        TreeNode87.Name = "96"
        TreeNode87.Text = "3.5.2 离散型随机变量的独立性（13题）"
        TreeNode88.Name = "97"
        TreeNode88.Text = "3.5.3 连续型随机变量的独立性（7题）"
        TreeNode89.Name = "99"
        TreeNode89.Text = "3.5.4.1 二项变量、泊松变量的独立性"
        TreeNode90.Name = "100"
        TreeNode90.Text = "3.5.4.2 均匀变量、指数变量的独立性"
        TreeNode91.Name = "101"
        TreeNode91.Text = "3.5.4.3 正态变量的独立性"
        TreeNode92.Name = "节点62"
        TreeNode92.Text = "3.5.4 常见随机变量的独立性（11题）"
        TreeNode93.Name = "103"
        TreeNode93.Text = "3.5.5 n维随机变量的独立性（0题）"
        TreeNode94.Name = "节点36"
        TreeNode94.Text = "3.5 随机变量的独立性（31题）"
        TreeNode95.Name = "105"
        TreeNode95.Text = "3.6.1 二维离散型随机变量的函数的分布（8题）"
        TreeNode96.Name = "106"
        TreeNode96.Text = "3.6.2 二维连续型随机变量的函数的分布（19题）"
        TreeNode97.Name = "107"
        TreeNode97.Text = "3.6.3 最大、最小函数的分布（14题）"
        TreeNode98.Name = "108"
        TreeNode98.Text = "3.6.4 离散型与连续型随机变量的函数的分布（0题）"
        TreeNode99.Name = "109"
        TreeNode99.Text = "3.6.5 n维随机变量的函数的分布（5题）"
        TreeNode100.Name = "节点37"
        TreeNode100.Text = "3.6 多维随机变量的函数的分布（46题）"
        TreeNode101.Name = "节点2"
        TreeNode101.Text = "第3章 多维随机变量及其分布（185题）"
        TreeNode102.Name = "113"
        TreeNode102.Text = "4.1.1 数学期望的概念与性质（30题）"
        TreeNode103.Name = "116"
        TreeNode103.Text = "4.1.2.1 离散型随机变量的期望（18题）"
        TreeNode104.Name = "117"
        TreeNode104.Text = "4.1.2.2 连续型随机变量的期望（13题）"
        TreeNode105.Name = "节点78"
        TreeNode105.Text = "4.1.2 期望计算（31题）"
        TreeNode106.Name = "162"
        TreeNode106.Text = "4.1.3.1 一维离散型随机变量的函数的期望（9题）"
        TreeNode107.Name = "163"
        TreeNode107.Text = "4.1.3.2 一维连续型随机变量的函数的期望（12题）"
        TreeNode108.Name = "164"
        TreeNode108.Text = "4.1.3.3 二维离散型随机变量的函数的期望（1题）"
        TreeNode109.Name = "165"
        TreeNode109.Text = "4.1.3.4 二维连续型随机变量的函数的期望（11题）"
        TreeNode110.Name = "节点79"
        TreeNode110.Text = "4.1.3 随机变量函数的期望（33题）"
        TreeNode111.Name = "122"
        TreeNode111.Text = "4.1.4 期望应用（0题）"
        TreeNode112.Name = "节点72"
        TreeNode112.Text = "4.1 数学期望（94题）"
        TreeNode113.Name = "124"
        TreeNode113.Text = "4.2.1 方差的概念与性质（27题）"
        TreeNode114.Name = "129"
        TreeNode114.Text = "4.2.2.1 离散型随机变量的方差（3题）"
        TreeNode115.Name = "130"
        TreeNode115.Text = "4.2.2.2 连续型随机变量的方差（15题）"
        TreeNode116.Name = "节点90"
        TreeNode116.Text = "4.2.2 方差计算（18题）"
        TreeNode117.Name = "132"
        TreeNode117.Text = "4.2.3.1 一维离散型随机变量的函数的方差（0题）"
        TreeNode118.Name = "133"
        TreeNode118.Text = "4.2.3.2 一维连续型随机变量的函数的方差（0题）"
        TreeNode119.Name = "134"
        TreeNode119.Text = "4.2.3.3二维离散型随机变量的函数的方差（0题）"
        TreeNode120.Name = "135"
        TreeNode120.Text = "4.2.3.4 二维连续型随机变量的函数的方差（0题）"
        TreeNode121.Name = "节点91"
        TreeNode121.Text = "4.2.3 随机变量的函数的方差（0题）"
        TreeNode122.Name = "136"
        TreeNode122.Text = "4.2.4 切比雪夫不等式（25题）"
        TreeNode123.Name = "137"
        TreeNode123.Text = "4.2.5 方差应用（0题）"
        TreeNode124.Name = "节点73"
        TreeNode124.Text = "4.2 方差（70题）"
        TreeNode125.Name = "168"
        TreeNode125.Text = "4.3.1.1 常见离散型分布的期望与方差（12题）"
        TreeNode126.Name = "169"
        TreeNode126.Text = "4.3.1.2 常见连续型分布的期望与方差（11题）"
        TreeNode127.Name = "节点100"
        TreeNode127.Text = "4.3.1 常见分布的期望与方差（23题）"
        TreeNode128.Name = "171"
        TreeNode128.Text = "4.3.2.1 离散型随机变量的期望与方差（4题）"
        TreeNode129.Name = "172"
        TreeNode129.Text = "4.3.2.2 离散型随机变量函数的期望与方差（1题）"
        TreeNode130.Name = "节点101"
        TreeNode130.Text = "4.3.2 一般离散型分布的期望与方差（5题）"
        TreeNode131.Name = "174"
        TreeNode131.Text = "4.3.3.1 连续型随机变量的期望与方差（3题）"
        TreeNode132.Name = "175"
        TreeNode132.Text = "4.3.3.2 连续型随机变量函数的期望与方差（8题）"
        TreeNode133.Name = "节点102"
        TreeNode133.Text = "4.3.3 一般连续型分布的期望与方差（11题）"
        TreeNode134.Name = "节点92"
        TreeNode134.Text = "4.3 期望与方差计算（39题）"
        TreeNode135.Name = "139"
        TreeNode135.Text = "4.4.1 协方差的概念与性质（10题）"
        TreeNode136.Name = "140"
        TreeNode136.Text = "4.4.2 协方差计算（0题）"
        TreeNode137.Name = "141"
        TreeNode137.Text = "4.4.3 相关系数的概念与性质（8题）"
        TreeNode138.Name = "142"
        TreeNode138.Text = "4.4.4 相关系数计算（23题）"
        TreeNode139.Name = "143"
        TreeNode139.Text = "4.4.5 随机变量的不相关性（8题）"
        TreeNode140.Name = "145"
        TreeNode140.Text = "4.4.6 相关系数应用（0题）"
        TreeNode141.Name = "节点74"
        TreeNode141.Text = "4.4 协方差与相关系数（49题）"
        TreeNode142.Name = "147"
        TreeNode142.Text = "4.5.1 矩的概念（5题）"
        TreeNode143.Name = "148"
        TreeNode143.Text = "4.5.2 矩计算（0题）"
        TreeNode144.Name = "146"
        TreeNode144.Text = "4.5 矩（5题）"
        TreeNode145.Name = "节点3"
        TreeNode145.Text = "第4章 随机变量的数字特征（257题）"
        TreeNode146.Name = "155"
        TreeNode146.Text = "5.1.1 依概率收敛（0题）"
        TreeNode147.Name = "156"
        TreeNode147.Text = "5.1.2 三个大数定理（5题）"
        TreeNode148.Name = "节点121"
        TreeNode148.Text = "5.1 大数定理（5题）"
        TreeNode149.Name = "157"
        TreeNode149.Text = "5.2.1 两个中心极限定理（9题）"
        TreeNode150.Name = "158"
        TreeNode150.Text = "5.2.2 两个中心极限定理的应用（17题）"
        TreeNode151.Name = "节点122"
        TreeNode151.Text = "5.2 中心极限定理（26题）"
        TreeNode152.Name = "节点4"
        TreeNode152.Text = "第5章 大数定理与中心极限定理（31题）"
        TreeNode153.Name = "178"
        TreeNode153.Text = "6.1.1 简单随机样本与样本的联合分布（7题）"
        TreeNode154.Name = "179"
        TreeNode154.Text = "6.1.2 直方图、条形图及经验分布函数（6题）"
        TreeNode155.Name = "节点127"
        TreeNode155.Text = "6.1 总体与样本（13题）"
        TreeNode156.Name = "181"
        TreeNode156.Text = "6.2.1 基本数字特征（33题）"
        TreeNode157.Name = "182"
        TreeNode157.Text = "6.2.2 简易数字特征（0题）"
        TreeNode158.Name = "节点128"
        TreeNode158.Text = "6.2 样本的数字特征（33题）"
        TreeNode159.Name = "184"
        TreeNode159.Text = "6.3.1 分位数（0题）"
        TreeNode160.Name = "185"
        TreeNode160.Text = "6.3.2 χ2分布、t分布和F分布（28题）"
        TreeNode161.Name = "节点129"
        TreeNode161.Text = "6.3 三个常用的抽样分布（28题）"
        TreeNode162.Name = "187"
        TreeNode162.Text = "6.4.1 统计量的概念（6题）"
        TreeNode163.Name = "189"
        TreeNode163.Text = "6.4.2.1 单个正态总体的抽样分布定理（25题）"
        TreeNode164.Name = "190"
        TreeNode164.Text = "6.4.2.2 单个正态总体的抽样应用（19题）"
        TreeNode165.Name = "节点138"
        TreeNode165.Text = "6.4.2 单个正态总体的抽样分布（44题）"
        TreeNode166.Name = "192"
        TreeNode166.Text = "6.4.3.1 两个正态总体的抽样分布定理（13题）"
        TreeNode167.Name = "193"
        TreeNode167.Text = "6.4.3.2 两个正态总体的抽样应用（9题）"
        TreeNode168.Name = "节点139"
        TreeNode168.Text = "6.4.3 两个正态总体的抽样分布（22题）"
        TreeNode169.Name = "194"
        TreeNode169.Text = "6.4.4 一般总体的抽样分布（16题）"
        TreeNode170.Name = "节点130"
        TreeNode170.Text = "6.4 常用统计量及其分布（88题）"
        TreeNode171.Name = "节点5"
        TreeNode171.Text = "第6章 样本与抽样分布（162题）"
        TreeNode172.Name = "198"
        TreeNode172.Text = "7.1.1 点估计与区间估计的概念（10题）"
        TreeNode173.Name = "199"
        TreeNode173.Text = "7.1.2 估计量（18题）"
        TreeNode174.Name = "节点145"
        TreeNode174.Text = "7.1 参数估计的概念（28题）"
        TreeNode175.Name = "202"
        TreeNode175.Text = "7.2.1.1 矩估计法（22题）"
        TreeNode176.Name = "203"
        TreeNode176.Text = "7.2.1.2 最大似然估计法（13题）"
        TreeNode177.Name = "节点150"
        TreeNode177.Text = "7.2.1 点估计的方法（35题）"
        TreeNode178.Name = "205"
        TreeNode178.Text = "7.2.2.1 无偏性（24题）"
        TreeNode179.Name = "206"
        TreeNode179.Text = "7.2.2.2 有效性和相合性（12题）"
        TreeNode180.Name = "节点151"
        TreeNode180.Text = "7.2.2 点估计量的评价准则（36题）"
        TreeNode181.Name = "节点146"
        TreeNode181.Text = "7.2 点估计（71题）"
        TreeNode182.Name = "210"
        TreeNode182.Text = "7.3.1.1 均值的区间估计（23题）"
        TreeNode183.Name = "211"
        TreeNode183.Text = "7.3.1.2 方差的区间估计（9题）"
        TreeNode184.Name = "节点156"
        TreeNode184.Text = "7.3.1 单个正态总体均值与方差的区间估计（32题）"
        TreeNode185.Name = "213"
        TreeNode185.Text = "7.3.2.1 均值差的区间估计（6题）"
        TreeNode186.Name = "214"
        TreeNode186.Text = "7.3.2.2 方差比的区间估计（4题）"
        TreeNode187.Name = "节点157"
        TreeNode187.Text = "7.3.2 两个正态总体均值差与方差比的区间估计（10题）"
        TreeNode188.Name = "215"
        TreeNode188.Text = "7.3.3 一般总体参数的区间估计（11题）"
        TreeNode189.Name = "节点147"
        TreeNode189.Text = "7.3 区间估计（53题）"
        TreeNode190.Name = "节点6"
        TreeNode190.Text = "第7章 参数估计（152题）"
        TreeNode191.Name = "220"
        TreeNode191.Text = "8.1.1 假设检验问题（9题）"
        TreeNode192.Name = "221"
        TreeNode192.Text = "" & Global.Microsoft.VisualBasic.ChrW(9) & "8.1.2 假设检验中的两类错误（15题）"
        TreeNode193.Name = "节点163"
        TreeNode193.Text = "8.1 假设检验的基本概念（24题）"
        TreeNode194.Name = "224"
        TreeNode194.Text = "8.2.1.1 均值检验（33题）"
        TreeNode195.Name = "225"
        TreeNode195.Text = "8.2.1.2 方差检验（20题）"
        TreeNode196.Name = "节点169"
        TreeNode196.Text = "8.2.1 单个正态总体参数的假设检验（53题）"
        TreeNode197.Name = "226"
        TreeNode197.Text = "8.2.2.1 均值差检验（27题）"
        TreeNode198.Name = "227"
        TreeNode198.Text = "8.2.2.2 方差比检验（11题）"
        TreeNode199.Name = "节点170"
        TreeNode199.Text = "8.2.2 两个正态总体参数的假设检验（38题）"
        TreeNode200.Name = "节点164"
        TreeNode200.Text = "8.2 正态总体参数的假设检验（91题）"
        TreeNode201.Name = "228"
        TreeNode201.Text = "8.3 一般总体参数的假设检验（17题）"
        TreeNode202.Name = "229"
        TreeNode202.Text = "8.4 总体分布的假设检验（12题）"
        TreeNode203.Name = "节点7"
        TreeNode203.Text = "第8章 假设检验（144题）"
        Me.TreeView1.Nodes.AddRange(New System.Windows.Forms.TreeNode() {TreeNode33, TreeNode60, TreeNode101, TreeNode145, TreeNode152, TreeNode171, TreeNode190, TreeNode203})
        Me.TreeView1.Size = New System.Drawing.Size(776, 426)
        Me.TreeView1.TabIndex = 1
        '
        'FormSelectPT
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(800, 450)
        Me.ControlBox = False
        Me.Controls.Add(Me.TreeView1)
        Me.KeyPreview = True
        Me.Name = "FormSelectPT"
        Me.ShowInTaskbar = False
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent
        Me.Text = "Double Click To Choose A Chapter"
        Me.ResumeLayout(False)

    End Sub

    Friend WithEvents TreeView1 As TreeView
End Class
